-- MySQL Script generated by MySQL Workbench
-- Mon May 22 19:52:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbdoar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbdoar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbdoar` DEFAULT CHARACTER SET utf8 ;
USE `dbdoar` ;

-- -----------------------------------------------------
-- Table `dbdoar`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdoar`.`perfil` (
  `idperfil` INT(10) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbdoar`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdoar`.`usuario` (
  `idusuario` INT(10) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(60) NOT NULL,
  `idperfil` INT(10) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  INDEX `fk_usuario_perfil1_idx` (`idperfil` ASC),
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`idperfil`)
    REFERENCES `dbdoar`.`perfil` (`idperfil`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbdoar`.`doador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdoar`.`doador` (
  `cpfdoador` VARCHAR(60) NOT NULL,
  `rgdoador` VARCHAR(60) NOT NULL,
  `nomedoador` VARCHAR(60) NOT NULL,
  `telefonedoador` VARCHAR(60) NOT NULL,
  `emaildoador` VARCHAR(60) NOT NULL,
  `enderecodoador` VARCHAR(60) NOT NULL,
  `dtnascdoador` DATE NOT NULL,
  `idusuario` INT(10) NOT NULL,
  PRIMARY KEY (`cpfdoador`),
  UNIQUE INDEX `CPF_UNIQUE` (`cpfdoador` ASC),
  UNIQUE INDEX `RG_UNIQUE` (`rgdoador` ASC),
  INDEX `fk_doador_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_doador_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `dbdoar`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbdoar`.`instituto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdoar`.`instituto` (
  `idinstituto` INT(10) NOT NULL AUTO_INCREMENT,
  `nomeinstituto` VARCHAR(60) NOT NULL,
  `emailinstituto` VARCHAR(60) NOT NULL,
  `telefoneinstituto` VARCHAR(60) NOT NULL,
  `enderecoinstituto` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idinstituto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbdoar`.`representante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdoar`.`representante` (
  `idrepresentante` INT(11) NOT NULL AUTO_INCREMENT,
  `nomerep` VARCHAR(60) NOT NULL,
  `cpfrep` VARCHAR(60) NOT NULL,
  `rgrep` VARCHAR(60) NOT NULL,
  `dtnascrep` DATE NOT NULL,
  `enderecorep` VARCHAR(60) NOT NULL,
  `emailrep` VARCHAR(60) NOT NULL,
  `telefonerep` VARCHAR(60) NOT NULL,
  `sexo` VARCHAR(60) NOT NULL,
  `idinstituto` INT(10) NOT NULL,
  `idusuario` INT(10) NOT NULL,
  PRIMARY KEY (`idrepresentante`),
  UNIQUE INDEX `matricula_UNIQUE` (`idrepresentante` ASC),
  UNIQUE INDEX `RG_UNIQUE` (`rgrep` ASC),
  UNIQUE INDEX `CPF_UNIQUE` (`cpfrep` ASC),
  INDEX `fk_representante_Instituto1_idx` (`idinstituto` ASC),
  INDEX `fk_representante_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_representante_Instituto1`
    FOREIGN KEY (`idinstituto`)
    REFERENCES `dbdoar`.`instituto` (`idinstituto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_representante_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `dbdoar`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbdoar`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdoar`.`pedido` (
  `idpedido` INT(10) NOT NULL AUTO_INCREMENT,
  `nomepedido` VARCHAR(45) NOT NULL,
  `descricaopedido` VARCHAR(120) NOT NULL,
  `condicao` VARCHAR(60) NOT NULL,
  `status` INT NOT NULL DEFAULT 1 COMMENT '1==PENDENTE\n2==EM ANDAMENTO\n3==CONCLUIDO',
  `datapedido` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `quantidadepedido` VARCHAR(45) NOT NULL,
  `idinstituto` INT(10) NOT NULL,
  `idrepresentante` INT(11) NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_Instituto1_idx` (`idinstituto` ASC),
  INDEX `fk_pedido_representante1_idx` (`idrepresentante` ASC),
  CONSTRAINT `fk_pedido_Instituto1`
    FOREIGN KEY (`idinstituto`)
    REFERENCES `dbdoar`.`instituto` (`idinstituto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedido_representante1`
    FOREIGN KEY (`idrepresentante`)
    REFERENCES `dbdoar`.`representante` (`idrepresentante`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbdoar`.`doacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdoar`.`doacao` (
  `iddoacao` INT(10) NOT NULL,
  `nomedoacao` VARCHAR(60) NOT NULL,
  `descricaodoacao` VARCHAR(60) NOT NULL,
  `quantidadedoacao` VARCHAR(60) NOT NULL,
  `datadoacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `idrepresentante` INT(11) NOT NULL,
  `idpedido` INT(10) NOT NULL,
  `cpfdoador` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`iddoacao`),
  INDEX `fk_doacao_representante1_idx` (`idrepresentante` ASC),
  INDEX `fk_doacao_pedido1_idx` (`idpedido` ASC),
  INDEX `fk_doacao_doador1_idx` (`cpfdoador` ASC),
  CONSTRAINT `fk_doacao_doador1`
    FOREIGN KEY (`cpfdoador`)
    REFERENCES `dbdoar`.`doador` (`cpfdoador`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_doacao_pedido1`
    FOREIGN KEY (`idpedido`)
    REFERENCES `dbdoar`.`pedido` (`idpedido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_doacao_representante1`
    FOREIGN KEY (`idrepresentante`)
    REFERENCES `dbdoar`.`representante` (`idrepresentante`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
ALTER TABLE `dbdoar`.`doacao` 
CHANGE COLUMN `iddoacao` `iddoacao` INT(10) NOT NULL AUTO_INCREMENT ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

